apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    tier: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backend.port }}
    targetPort: http
  type: {{ .Values.service.backend.type }}
