apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: amazon/aws-cli:2.9.20
        command: ["/bin/sh", "-c", 'curl -X POST --data-urlencode payload="{\"text\": \"App Sync succeeded on $ENV environment. Test message\"}" $SLACK']
        env:
          - name: SLACK
            valueFrom:
              secretKeyRef:
                name: slack-test
                key: url    
          - name: ENV
            value: {{ .Values.environment }}                
      restartPolicy: Never
  backoffLimit: 2
