apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment }}
  namespace: {{ .Values.environment }}
  labels:
    name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
        - name: api-doc
          image: 541756307328.dkr.ecr.us-west-2.amazonaws.com/apidoc:latest
