apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontend.port }}
    targetPort: http
  type: {{ .Values.service.frontend.type }}
